import { useEffect, useMemo, useState } from "react";
import { FaHotel, FaPlaneDeparture, FaRegSave } from "react-icons/fa";

import AIAssistant from "../components/AIAssistant/AIAssistant";
import api from "../services/api";
import styles from "./AIPlanner.module.css";

const quickPrompts = [
  "Plan a trip to Bali",
  "Find cheap flights to Paris",
  "Best hotels in Tokyo under $100",
  "7-day Europe itinerary",
];

const asArray = (value) => (Array.isArray(value) ? value : []);

const money = (value) => {
  const amount = Number(value || 0);
  return Number.isFinite(amount) ? `$${amount.toFixed(2)}` : "$0.00";
};

const formatActivity = (activity) => {
  if (typeof activity === "string") return activity;
  if (!activity || typeof activity !== "object") return "Planned activity";

  const name = activity.name || activity.title || "Planned activity";
  const time = activity.time ? ` (${activity.time})` : "";
  const description = activity.description ? ` - ${activity.description}` : "";
  return `${name}${time}${description}`;
};

export default function AIPlanner() {
  const [sessionId] = useState(`session-${Date.now()}`);
  const [messages, setMessages] = useState([
    {
      id: 1,
      role: "assistant",
      message: "Hi! I'm TravelMind 🌍 Where are you headed?",
      timestamp: new Date().toISOString(),
    },
  ]);
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    const loadHistory = async () => {
      try {
        const { data } = await api.get(`/api/ai/history/${sessionId}`);
        if (data.length) setMessages(data);
      } catch (_) {}
    };
    loadHistory();
  }, [sessionId]);

  const sendMessage = async (text) => {
    const optimistic = {
      id: Date.now(),
      role: "user",
      message: text,
      timestamp: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, optimistic]);
    setLoading(true);
    setError("");

    try {
      const { data } = await api.post("/api/ai/chat", { session_id: sessionId, message: text });
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + 1,
          role: "assistant",
          message: data.reply,
          timestamp: new Date().toISOString(),
        },
      ]);
    } catch (err) {
      setError(err.response?.data?.detail || "Unable to fetch AI response");
    } finally {
      setLoading(false);
    }
  };

  const generatePlan = async (destination = "Bali") => {
    setLoading(true);
    setError("");
    try {
      const payload = {
        destination,
        start_date: new Date().toISOString().slice(0, 10),
        end_date: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString().slice(0, 10),
        budget: 1500,
        preferences: "culture, local food, relaxed pace",
      };
      const { data } = await api.post("/api/ai/plan-trip", payload);
      setPlan(data);
    } catch (err) {
      setError(err.response?.data?.detail || "Could not generate plan");
    } finally {
      setLoading(false);
    }
  };

  const saveToTrips = async () => {
    if (!plan?.itinerary?.length) return;
    try {
      await api.post("/api/trips", {
        title: `AI Trip Plan`,
        destination: plan.suggested_hotels?.[0]?.location || "Custom Destination",
        start_date: plan.itinerary[0]?.date || new Date().toISOString().slice(0, 10),
        end_date: plan.itinerary.at(-1)?.date || new Date().toISOString().slice(0, 10),
        budget: plan.estimated_cost,
        notes: "Generated by TravelMind AI planner",
        status: "planned",
      });
      alert("Trip saved to My Trips");
    } catch (err) {
      setError(err.response?.data?.detail || "Failed to save trip");
    }
  };

  const budgetBars = useMemo(() => {
    const total = Number(plan?.estimated_cost || 0) || 1;
    return [
      { label: "Flights", value: total * 0.4 },
      { label: "Hotels", value: total * 0.35 },
      { label: "Activities", value: total * 0.15 },
      { label: "Other", value: total * 0.1 },
    ];
  }, [plan]);

  return (
    <main className="page">
      <h1 className="section-title">AI Planner</h1>
      {error && <p className={styles.error}>{error}</p>}

      <div className={styles.split}>
        <div>
          <div className={styles.chips}>
            {quickPrompts.map((chip) => (
              <button key={chip} className="btn" onClick={() => sendMessage(chip)}>
                {chip}
              </button>
            ))}
            <button className="btn btn-primary" onClick={() => generatePlan("Bali")}>Generate Itinerary</button>
          </div>
          <AIAssistant messages={messages} onSend={sendMessage} loading={loading} />
        </div>

        <section className={`${styles.itineraryPanel} card`}>
          <h2>Live Itinerary Builder</h2>
          {!plan && <p>Use quick actions or ask TravelMind to generate your itinerary.</p>}

          {plan && (
            <>
              <div className={styles.timeline}>
                {plan.itinerary?.map((day, index) => (
                  <div key={`${day.date}-${index}`} className={styles.dayCard}>
                    <h4>Day {day.day || index + 1} • {day.date}</h4>
                    <p>{day.title}</p>
                    <ul>
                      {(day.activities || []).map((activity, i) => (
                        <li key={i}>{formatActivity(activity)}</li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>

              <div className={styles.suggestions}>
                <div className="card">
                  <h4><FaPlaneDeparture /> Suggested Flights</h4>
                  {asArray(plan.suggested_flights).length ? (
                    <ul className={styles.suggestList}>
                      {asArray(plan.suggested_flights).map((flight, index) => (
                        <li key={`${flight.airline || "flight"}-${index}`} className={styles.suggestItem}>
                          <strong>{flight.airline || "Airline"}</strong>
                          <span>{flight.origin || "Origin"} to {flight.destination || "Destination"}</span>
                          <span>
                            {flight.departure_time || flight.departure || "Any time"}
                            {flight.arrival_time ? ` -> ${flight.arrival_time}` : ""}
                          </span>
                          <small>{money(flight.price)}</small>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className={styles.emptyText}>No flight suggestions available yet.</p>
                  )}
                </div>
                <div className="card">
                  <h4><FaHotel /> Suggested Hotels</h4>
                  {asArray(plan.suggested_hotels).length ? (
                    <ul className={styles.suggestList}>
                      {asArray(plan.suggested_hotels).map((hotel, index) => (
                        <li key={`${hotel.name || "hotel"}-${index}`} className={styles.suggestItem}>
                          <strong>{hotel.name || hotel.hotel_name || "Hotel"}</strong>
                          <span>{hotel.location || "Destination area"}</span>
                          {hotel.rating ? <span>Rating: {hotel.rating}</span> : null}
                          <small>{money(hotel.price_per_night || hotel.price)}</small>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p className={styles.emptyText}>No hotel suggestions available yet.</p>
                  )}
                </div>
              </div>

              <div className={`${styles.budget} card`}>
                <h4>Estimated Budget: ${Number(plan.estimated_cost || 0).toFixed(2)}</h4>
                {budgetBars.map((item) => (
                  <div key={item.label}>
                    <span>{item.label}</span>
                    <div className={styles.barTrack}>
                      <div className={styles.barFill} style={{ width: `${(item.value / (plan.estimated_cost || 1)) * 100}%` }} />
                    </div>
                  </div>
                ))}
              </div>

              <div className={styles.actions}>
                <button className="btn btn-primary" onClick={saveToTrips}>
                  <FaRegSave /> Save to My Trips
                </button>
                <button className="btn" onClick={() => window.print()}>Export as PDF</button>
              </div>
            </>
          )}
        </section>
      </div>
    </main>
  );
}
